# Introduction

## Basic Information

This assessment reports the status of `r spp` (*Sebastes hopkinsi*) off the U.S. West Coast using data through 2020. `r Spp` is a relatively small rockfish found from Mexico to southern Oregon, with a core distribution in southern California. This species is treated as one stock, as there is no evidence of population structure.


## Life History

`r Spp` is a dwarf species of rockfish commonly found in depths between 60 - 123 m (33-68 fm), hovering over or sheltering in rocky reef habitat and aggregating with other smaller rockfishes [@love_milton_rockfishes_2002]. `r Spp` are yellow-brown, brown, or tan on the back and sides with lighter colored bellies. `r Spp`  has sex-specific growth with females reaching larger sizes (29 cm) than males (23 cm). They are mainly plantivores, eating crustaceans such as cyrinid larvae.


## Historical and Current Fishery Information

Squarespot rockfish are generally undesirable in the recreational and commercial fishery due to their small size (@love_milton_rockfishes_2002).  Females grow larger than males, and only nearing their maximum length do they reach a size that is marginally acceptable to anglers, thus the landings are primarily composed of older females.  While there is some anecdotal evidence of directed commercial fishing using small hooks, they are often discarded as bycatch and commercial catch is relatively low over the entire catch history.  The stock has been managed as part of the Minor Shelf Rockfish South Complex since 2000, for which access for both the commercial and recreational fisheries have been restricted with rockfish conservation areas (RCAs) to rebuild overfished stocks (Appendix A).   

In the early part of the 20th century the California recreational fishery was focused on nearshore waters near ports, but expanded further from port and into deeper depths over time [@miller_spatially_2014].  Prior to the rebuilding period for overfished species after the groundfish fishery disaster was declared in 2000, there was access to all depths and seasons for groundfishes (Appendix A).  Most of the catch of `r spp` in the recreational fishery comes from south of Point Conception, consistent with the species range.  For areas north of Point Conception to Pigeon Point near Santa Cruz (the northern extent of `r spp` range), the shallow depth limit of the Rockfish Conservation Area was 40 fm (73 m) and was increased to 50 fm (91 m) in 2017, both provides some protection for `r spp`.  South of Point Conception the depth restrictions were 20 to 60 fm (36-110 m) after 2000, providing more access compare to the north, until 2019 when depth restrictions started at 75 fm (137 m), then to 100 fm (183 m) in 2021.  This depth restriction change was due to the rebuilding of cowcod, providing access to the majority of the `r spp` depth range as they are found as deep as 123 fm, but are common to 83 fm [@love_milton_rockfishes_2002].     

## Summary of Management History and Performance

`r Spp` is managed by the Pacific Fishery Management Council (PFMC) as a part of the Minor Shelf Rockfish North and South complexes.  The North and South areas are split at N. 40$^\circ$ 10' Lat. N. off the West Coast. While `r spp` is included in the Shelf Rockfish North complex, the OFL contribution from `r spp` is extremely low (< 0.5 mt) because the vast majority of the distribution of the stock is in the southern region of California. The Shelf Rockfish complex is managed based on a complex level overfishing limit (OFL) and annual catch limit (ACL). The complex OFLs and ACLs are determined by summing the species specific OFLs and ACLs managed within the complex. Removals for species within the Minor Shelf Rockfish complex are managed and tracked against the complex total OFL and ACL, rather than on a species by species basis.

The OFL and ACLs contributions for `r spp` South of 40$^\circ$ 10' Lat. N. management area and the total removals south of Pt. Conception are shown in Table \ref{tab:ofl}.



