## Fishery-Dependent Data

### Recreational Fishery

#### Removals
The recreational removals prior to 1980 were obtained from the historical reconstruction starting in 1928 [@ralston_documentation_2010]. Recreational removals from 1980 - 2003 were obtained from MRFSS and provide total mortality (observed landings plus dead discarded and unavailable fish).  Missing years of removals (1990-1992) were assumed by applying a linear ramp in removals based on 1989 and 1993 removals. Removals in years 2004 - 2020 were derived from samples taken by the California Recreational Fisheries Survey (CRFS). CRFS reported removals combine estimates of retained, dead discarded, and unreported landings. Both the MRFSS and CRFS reported removals were downloaded from RecFIN. 

Estimates of recreational discard mortality for the period 1980 - 2020 are based on angler reported discards that can underestimate removals of less desirable species. Underestimation may occur because recall of encounters with undesirable species can be low, as well as $Sebastes$ indentification issues among anglers (at least 36 rockfishes are regularly encountered in the recreational fishery).  Since 2008, efforts have been made to improve anglers' species identification skills by distributing over 20,000 laminated groundfish identification guides and posters to CPFVs to improve compliance with species specific regulations. 

Onboard observers record species of fish retained and discarded for a subset of anglers along each drift. Comparisons of the discard rates calculated from retained and discarded catch estimates to those calculated from onboard sampling observations of the composition of retained and discarded fish tallied by the observer the actual discard of squarespot by up to a factor of 3. Two model sensitivities to discard rates were performed: 1) increasing the discard by a factor of 3 (the average disard rate across years 2005-2016) applied to the entire timeseries; 2) Increase discards by a factor of 10.5 through 2008 (based on the average discard rate from 2005-2008), after which discards are increased by 2.7 (based on the average discard rate from 2009-2016). 


#### Length Compositions
Length data (Figure \ref{fig:rec-len-data}) for retained recreational catches sourced by MRFSS (1980-2003) and CRFS (2004-2020) were downloaded from the RecFIN website. The lengths of discarded fish measured by samplers onboard CPFVs prior to being released (Type 3d data) from 2003 to 2020 were also downloaded from the RecFIN website.  The number of length observations by year are shown in Table \ref{tab:rec-len}. The highest samples by year occurred within the last 16 years of the modeled period. The recreational lengths provide little information regarding recruitment strength in the length data as only the largest individuals (with a broad range of unknown age) are taken (Figure \ref{fig:rec-len-data}).  The mean size observed ranged between about 20 to 25 cm (Figure \ref{fig:rec-mean-len-data}). The small size of `r spp` and typical hook size used in the recreational fishery likely limits the ability of hook and line gear to observe smaller fish. Input sample sizes were assumed equal to the number of length samples available by year. 

### Commercial Fishery

#### Removals
The commercial removals for `r spp` are extremely sparse throughout the time series (Figure \ref{fig:twofleetcatch}). The small size of `r spp` individuals makes `r spp` an undesirable fish to market and to capture by trawl or commercial hook and line gears. Its affinity for rocky reefs also makes it difficult to access with trawl gear. Commercial landings prior to 1969 were queried through the SWFSC California Catch Reconstruction database [@ralston_documentation_2010]. Landings in this database are divided into 'trawl', 'non-trawl', and 'unknown' gear categories. Commercial landings between 1969 - 1980 were queried from the CALCOM database. Commercial fishery landings from 1981-2020 were pulled from the PacFIN database, extracted 22 February, 2021. 

The input catches in the model represent total removals: landings plus discards.  Discards totals for the commercial fleet from 2002-2019 were determined based on West Coast Groundfish Observer Program (WCGOP) data provided in the Groundfish Expanded Mortality Multiyear (GEMM) product. The historical commercial discard mortality was calculated based on the average discard rates from WCGOP of 28 percent and used to adjust the landings data from `r startyr` to 2001 to account for total removals. 

Given the extremely small commercial landings and minimal sampling of lengths (see below), the recreational and commercial catches were combined into a single fleet by aggregating across gear types (Table \ref{tab:allcatches} and Figure \ref{fig:catch}).

#### Length Compositions
The annual length samples from the commercial fishery were quite limited (Table \ref{tab:com-len}).  The limited sizes observed were generally between 20 - 30 cm (Figure \ref{fig:comm-mean-len-data} and Figure \ref{fig:bubble-comm-len-data}). Given the small number of samples by year and the lack of commercial catches in the removal time series, the commerical removals were added to the recreational samples and the commercial lengths were excluded from the reference model. 

A sensitivity to using 2 fleets (commerical and recreational) as opposed to a combined 1 fleet was explored. This scenario separated the removals into two fleets and used the limited commerical lengths to estimate commerical selectivity. 

