## Fishery-Independent Data

### NWFSC Hook and Line Survey

Since 2004, the NWFSC has conducted an annual hook and line survey targeting shelf rockfishes (genus *Sebastes*) at fixed stations (e.g., sites, Figure \ref{fig:hkl-sites}) in the Southern California Bight. Key species of rockfish targeted by the \gls{s-hkl} are bocaccio (*S. paucispinis*), cowcod (*S. levis*), greenspotted (*S. chlorostictus*), and vermilion/sunset (*S. miniatus* and *S. crocotulus*) rockfishes, although a wide range of rockfish species have been observed by this survey. During each site visit, three deckhands simultaneously deploy 5-hook sampling rigs (this is referred to as a single drop) for a maximum of 5 minutes per line, but individual lines may be retrieved sooner at the angler's discretion (e.g., to avoid losing fish). Five drops are attempted at each site for a maximum possible catch of 75 fish per site per year (3 anglers x 5 hooks x 5 drops). Further details regarding the sample frame, site selection, and survey methodology are described by Harms et al. [@harms_noaa_2008]. 

`r Spp` have been observed at multiple sampling sites by the \Gls{s-hkl} survey each year between 2004 - 2019 (Table \ref{tab:hkl-len}). The number of positive observations increased sharply starting in 2014 which coincided with when the \gls{s-hkl} began sampling sites located within the Cowcod Conservation Area (CCA, Figure \ref{fig:hkl-cca}).  The increased observation rate starting in 2014 appeared to occur both outside and inside the CCA, rather than being due to the commencement of sampling within the CCA. The increased observations of `r spp` outside the CCA indicates that this change may be driven by recent strong year classes rather than a change in sampling location (John Harms, NOAA NWFSC, pers. comm.).    

The `r spp` observed by the \Gls{s-hkl} are primarily mature females which is likely due to the small size of male `r spp`, competition among other rockfishes, and hook size (Figure \ref{fig:hkl-len-data}). The mean size of fish observed by the \Gls{s-hkl} has been relatively stable (Figure \ref{fig:mean-hkl-len-data}). The small size of `r spp` may also make it an inconsistently collected species in this survey, but it was considered worth evaluating an index of abundance. The input sample sizes of lengths that accompany the survey samples were set equal to the number of length samples available by year. 

An annual index of abundance was calculated from the \Gls{s-hkl} data following the methods put forth in Harms et al. [-@harms_analysis_2010] based on the AIC criterion. The index of abundance was calculated using a binomial generalized-linear model. The final index includes year, site, number of hooks, fisher, drop number, and moon fullness (as a polynomial) as covariates.  The single index of abundance was calculated using both observation outside and within the CCA (Table \ref{tab:hkl-index-vals} and Figure \ref{fig:hkl-index}).  The index of abundances was low and relatively flat until 2014 when the index sharply increases, hitting a high in 2018. There seems to be no significant difference between indices that include or exclude samples from the CCA (Figure \ref{fig:mean-hkl-len-data}).



### NWFSC West Coast Groundfish Bottom Trawl Survey

The \gls{s-wcgbt} is based on a random-grid design; covering the coastal waters from a depth of 55-1,280 m [@bradburn_2003_2011]. This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two 'passes' of the coast. Two vessels fish from north to south during each pass between late May to early October. This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders.

The \gls{s-wcgbt} has observed `r spp` each year of the survey, however, the number of positive tows are limited (Table \ref{tab:wcgbts-len}). Since the \Gls{s-wcgbt} uses trawl gear to sample sandy bottom areas off the West Coast, it is not expected to be an informative data source for `r spp` which are small and closely associated with rock substrate. The limited tows by year where `r spp` were observed within this area, preventing the calculation of an index of abundance using spatial temporal methods (e.g., VAST) for `r spp`. A design-based index calculated resulted in high variability and uncertainty by year (Figure \ref{fig:wcgbts-dbindex}).  With limited length observations and in the absence of a VAST index of abundance to link these data to, this data set was not used in the base model.
 
Although these data were not used as an abundance index in the assessment, biological data from this survey were used to develop life history parameters.  The \gls{s-wcgbt} captured smaller fish relative to \gls{s-hkl} with both males and females observed (Figure \ref{fig:wcgbts-len-data}), particularly useful for estimating growth parameters. Samples collected by the \gls{s-wcgbt} were used to estimate sex specific length-at-weight, growth parameters, and to determine a prior value for natural mortality (see the [Biological Data](#biological_data) section below for more information).

### Triennial Survey

The \gls{s-tri} had limited observations of `r spp` (Table \ref{tab:tri-len}). Given the few positive tows these data were not used in the assessment. 
