# Assessment Model

## Summary of Previous Assessments 

Depletion Corrected Average Catch (DCAC) was used to set annual catch limits (ACLs) for `r spp` since 2010 [@dick_estimates_2010]. DCAC estimates the mean sustainable yield as 5.7 mt (median of 5.9 mt). This method assumed `r spp` relative stocks status was at 40% in 2009.


### Modelling Platform

Stock Synthesis version 3.30.16 was used as the statistical catch-at-age modelling framework. The SS-DL tool (https://github.com/shcaba/SS-DL-tool) was used for model exploration, likelihood profiling, and sensitivity analyses. The companion R package r4ss, version 1.38.0, along with R version 4.0.5 were used to investigate and plot model fits. 


### Bridging Analysis

No bridgining analysis between the DCAC model and Stock Synthesis was conducted given the significant structural differences (e.g., DCAC is an analytical approach) between the methods.


## Model Structure and Assumptions

The model assumes a "data-moderate" category 2 approach, meaning removal histories, length compositions and fishery-independent abundancies are the approved data inputs. Other data types (e.g., ages) can be used external to the assessment model to inform parameter values. The `r spp` model assessment assumes a single removal fleet (mainly recreational that includes the very small commercial catches) with removals starting in `r startyr`. The NWFSC Hook and Line survey is the one fishery-independant data source used to measure abundance trends. Selectivities for the fleet and survey were specified using the double normal parameterization within SS where selectivity was fixed to be asymptotic with the ascending slope and size of maximum selectivity parameters estimated. Life history parameters are sex-specific, with one growth type, and assumed stationary. Recruitment assumes a Beverton-Holt stock-recruit relationship and is deterministic.   


### Estimated and Fixed Parameters

All life history parameters are fixed to values described in the Biology section (2.3). Estimated parameters in the model are the two selectivity parameters each for the fleet and survey selectivities, and the log of the initial recruitment ($logR_0$). Sensitivity scenarios and likelihood profiles were used to explore uncertainty in the values of the natural mortality and growth parameters. When estimating parameters, the prior for natural mortality was assumed lognormal with a standard deviation of 0.22 (based on the prior developed using the Natural Mortality Tool (see Biology section for more details)), and the prior for the growth parameters ($L_{\infty}$ and $k$) was assumed normal with the mean equal to the fixed value with a CV of 10% (this is equal to assumed CV at length in the reference model, and maintains the ratio of variance between $L_{\infty}$ and $k$).


### Data Weighting

The reference model estimates additional variance on the NWFSC Hook and Line survey data to allow the model to balance model fit to that data while acknowledging that variances may be underestimated in the index standardization. The input CVs range from 30%-70% (Table \ref{tab:hkl-index-vals}). A sensitivity was run with no extra variance estimated, as well as removal of the index data.

Initial sample sizes for the recreational length compositions and NWFSC Hook and Line survey were based on the number of fish sampled. The method of Francis (-@francis_data_2011, equation TA1.8) was then used to balance the length composition data among other data inputs and likelihood components. The Francis method treats mean length as an index, with effective sample size defining the variance around the mean. If the variability around the mean does not encompass model predictions, the length data should be down-weighted until predictions fit within the intervals. This method accounts for correlation in the data (i.e., the multinomial distribution), but can be sensitive to years that are outliers, as the amount of down-weighting is applied to all years within a data source, and are not year-specific. Sensitivities were performed examining different data-weighting treatments: 1) the Dirichlet-Multinomial approach [@thorson_model-based_2017], 2) the McAllister-Ianelli Harmonic Mean approach [@mcallister_bayesian_1997], or 3) no data-weighting of lengths.



## Model Selection and Evaluation

The base assessment model for `r spp` was developed to balance parsimony and realism, and the goal was to estimate a spawning output trajectory and realtive stock status for the population of `r spp` in federal waters off California. The model contains many assumptions to achieve parsimony and uses different data types and sources to estimate reality. A series of investigative model runs were conducted to achieve the final base model. These include considerations of model structure, data and parameter treatment, estimation phasing, and jittered starting values to achieve a converged and balanced model that provides sensible parameter estimates and derived quantities.

