## Uncertainty exploration


### Sensitivity Analyses

Sensitivity analyses were conducted to evaluate model sensitivity to alternative data treatment and model specifications.

#### Data treatment sensitivities

Data treatments explored were as follows:

1. Data removal
	+ Fishery length data only (no catches)
  	+ Remove fishery length data
  	+ No survey data
  	+ No extra variance estimated for the survey
2. Data weighting
  	+ Dirichlet data-weighting
  	+ McAllister-Ianelli data weighting
  	+ No data-weighting
3. Removal history
  	+ Alternative discards I: 3 times discard rate 
  	+ Alternative discards II: 10.5 (up to 2009), then 2.7 times discard rate thereafter
  

Likelihood values and estimates of key parameters and derived quantities from each sensitivity are available in Table \ref{tab:data_sensis}. Derived quantities relative to the reference model are provided in Figure \ref{fig:sensi-data-RE}. Time series of spawning output and relative spawning output are shown in Figures \ref{fig:sensi-data-ssb} and \ref{fig:sensi-data-depl}.

The decision to allow the model to find a compromised fit between the weighted length data and the Hook and Line survey index via added variance on the index showed the largest relative change. A model that did not downweight the Hook and Line index showed a more optimistic relative spawning output, with the scale of the population outside the confidence intervals of the reference model (Figure \ref{fig:sensi-data-RE}). The scaleless length-only model provides a very similar estimate of final relative spawning output to the reference model (36.9% vs 37.5%), thus showing the influence of the length information. The scenario that removes all lengths resulted in a lower relative stock size, but has nothing to inform the removal selectivity, thus the results are highly dependent on the starting values of an unstable model.

Data-weighting choice had very little influence on model output. This also highlights that the simple fleet structure, limited additional data types, and fixed life history parameters puts a focus on the signal contained in the fishery length data. There was little influence in any derived quantities when adding three times more discards in the contemporary time frame (Figure \ref{fig:sensi-data-RE}). There was a little more sensitivity in the population scale adding 10 times more discards prior to 2009. This is a typical result when the catch history is adjusted upwards, which simply scales the popualtion size up as well. The model also added a little less variance to the Hook and Line index (Table \ref{tab:data_sensis}), but in general even adding 10 times more discards had very little impact in model results. Overall, the effects of all these data treatments are small.


#### Model specification sensitivities

Model specifications looked at the estimation of indiviual and combinations of life history parameters, the estimation of recruitment, and the use of two fleets (commercial and recreational) instead of one, and the hypothesis of five growth platoons instead of one. Each of the five life history estimation model specifications listed below were done for both sexes, just females and just males, for a total of 15 scenarios. All scenarios match the reference model specificatins in all other aspects unless otherwised stated.

1. Life history estimation
 + Estimate natural mortality ($M$)
  + Estimate $L_{\infty}$
  + Estimate $k$
  + Estimate $L_{\infty}$ and $k$
  + Estimate $M$, $L_{\infty}$ and $k$
  
2. Recruitment estimation and variability ($\sigma_R$). All years are estimated with bias correction applied.
	+ $\sigma_R$ = 0.45
	+ $\sigma_R$ = 0.6
	+ $\sigma_R$ = 0.75
	+ $\sigma_R$ = 0.6 with no extra variance

3. Miscellaneous
	+ 2 fleets (commerical and recreational instead of just one lumped fleet)
	+ 5 growth platoons instead of just one
  + Estimate dome-shaped selectivity after 2001
  + Estimate dome-shaped selectivity before and after 2001, but in two blocks

Likelihood values and estimates of key parameters and derived quantities from each sensitivity are available in Tables \ref{tab:modspec_LH_sensis} and \ref{tab:modspec_RecMisc_sensis}. Any attempt to estimate female $M$ and or $k$ led to unrealistic life history parameters estimates or population sizes (Table \ref{tab:modspec_LH_sensis}), so these runs are not included in the sensitivity figures in order to maintain an informative presentation. Derived quantities relative to the reference model are provided in Figure \ref{fig:sensi-modspec-RE}. Time series of spawning output and relative spawning output are shown in Figures \ref{fig:sensi-modspec-ssb} and \ref{fig:sensi-modspec-depl}.

Life history estimation involving female growth values tended to increase stock scale and current relative stock status, while male estimation tended to drop the estimate of unfished stock size, with slight overall increases in current relative stock status. 

A reference model that included recruitment estimation (assuming $\sigma_R$ = 0.6) was under consideration, but the model showed very little ability to estimate recruitment (Figure \ref{fig:rec-mod-var}). This is unsurprising given the fishery only takes the largest females, thus selectivity greatly weakens any recruitment signal. Estimating recruitment caused stock scale to decrease to around the bottom end of the reference model confidence intervals, but with a slight decrease in relative stock status. Downweighting the survey, as done in the reference model, causes the current biomass to increase with a significant increase in relative stock status. 

Breaking the fishery data into two fleets made little difference, thus supporting the parsimony of using one fleet. Hypothesizing five growth platoons instead of just one led to the notable result of higher stock scale and relative stock status. This approach causes two of five proposed female growth platoons to be below and two above the average (i.e., equivalent to the reference model) growth response. Given the fishery only takes the largest individuals, the smaller growth platoons are no longer available to the fishery, thus the population gains overall stock size and relative stock status.

The two dome-shaped selectivity scenarios are subsets of a larger exploration of dome-shaped selectivity requested after the first stock assessment review. Estimating dome-shaped selectivity after 2001 shifts the ascending selectivity to the right and a drop in selectivity before the size at $L_{\infty}$, resulting in a selectivity curve that full captures only a very restricted portion of length classes (Figure \ref{fig:dome-shaped}). This protection of the majority of the lengths after 2001 increases cryptic biomass and thereore results in a much more optimistic estimate of stock scale and status (Figure \ref{fig:Comp-ref-domes}). It also leads to huge increases in uncertainty of these derived quantities. Given biological parameters and recruiment deviations are not estimated, this huge increase in uncertainty is indicative of a lack of ability for the model to estimate selectivity parameters. It is also expected that the asymptotic version of the model would be at the lower limit of the uncertainty envelop, as it represents a boundary condition (i.e., one cannot select more than 100% of any length class). This uncertinaty grows if both periods are allowed to be selectivity. These results indicate the lack of capacity of the model to freely estimate dome-shaped selectivity, thus the decision to retain the default of asymptotic selectivity was retained. 

Overall, there were no model specification sensitivity scenarios that caused the population to drop significantly below the reference model estimate of stock status. If stock scale differed, unfished stock size had the largest uncertainty and was usually less than the reference model, excepting the hypothesis of five growth platoons.


### Likelihood Profiles

Likelihood profiles were conducted for $log(R_0)$, steepness ($h$), female and male natural mortality ($M$) values separately and varying together, female and male maximum length ($L_{\infty}$), female and male growth coefficient ($k$), female and male variability of size at maximum age. In addition, joint profiles over  $L_{\infty}$ and $k$ (that maintains a -0.9 correlation structure between the parameters) were conducted for females and males separately as well as for female and male natural mortality. Likelihood profiles fix the featured parameter(s) at specific values across a range of values and estimating the remaining parameters. A likelihood profile offers insight into information on a given parameter or parameter pairing, while providing an additional way to describe uncertainty in the parameter by indentifying the range of parameters within 1.92 likelihood units of the refrence model.

The $log(R_0)$ profiles show strong support for the maximum likelhood value of `r round(log(model$derived_quants[model$derived_quants$Label == "Recr_Virgin",2]),2)` (Figure \ref{fig:r0-profile-combo}). Population size expectedly increases as $log(R_0)$ increases, with the increase in current biomass happening quicker than initial biomass, thus relative stock status increase towards unfished at high $log(R_0)$ values. This is explained by the harvest rate decreasing because the removal history is fixed and becomes relatively smaller compared to the overall biomass. Length data dominated the information content in the profile, with the index indicating a higher $log(R_0)$, partially explaining the increased stock status when the index is given more weight.l

The steepness profile showed data supported values from 0.45 to 1, with ranges of relative stock status from 30% to 40% (Figure \ref{fig:steepness-profile-combo}). $SB_0$ showed the largest change across steepness values, though the most informed portion of the profile did not change greatly. Length data dominated the information in the profile (Figure \ref{fig:steepness-profile-combo}). 

Natural mortality profiles for females (Figure \ref{fig:M_f-profile-combo}) and males (Figure \ref{fig:M_m-profile-combo}) highlight two important issues: 1) the inability for the data in this model to inform either of these parameters and 2) model derived values are sensitive to the value, mainly female $M$. Natural mortality values at the minimum likelihood values either goes toward unrealistically high (Figure \ref{fig:M_f-profile-combo}) or low (Figure \ref{fig:M_m-profile-combo}) $M$ values. The combined profile that varies female and male $M$ together behave similarly to the female likelihood profile, though with less change across values (Figure \ref{fig:M-multiprofile-combo}). Scale and relative stock status are most affected by the assumption of females rather than male $M$, as the females interact the most with the fishery.

Female growth profiles show a similar lack of information to estimate $L_{\infty}$, $k$, or CV at maximum age. Length compositions support a smaller $L_{\infty}$ when $k$ is fixed (Figure \ref{fig:Linf_F-profile-combo}) and a lower $k$ when $L_{\infty}$ is fixed (Figure \ref{fig:k_f-profile-combo}). A more realistic profile maintains the negative correlation bewtween $L_{\infty}$ and $k$ showing the lower $L_{\infty}$ value is preferred over a lower $k$ value (Figure \ref{fig:Linf_k_f-profile}). Changing either value has a large affect on stock scale and relative stock status. The profile over the variability at maximum age supported a lower value than in the model (Figure \ref{fig:CVold_f-profile-combo}). The lower values increased overall popluation size (particularly current biomass) and derived a noticeably higher current relative stock status.

Male growth profiles showed more information and less overall sensitivity than the female profiles. Length compositions from the fishery and survey strongly supported a slightly larger $L_{\infty}$ when $k$ is fixed (Figure \ref{fig:Linf_M-profile-combo}) and a much higher $k$ when $L_{\infty}$ is fixed (Figure \ref{fig:k_m-profile-combo}), though there is essentially no information in estimating male $k$. Relative stock status changes little across $L_{\infty}$ and $k$ values, but the population scale change is more pronounced. The joint $L_{\infty}$-$k$ profile showing the higher $L_{\infty}$ value is preferred over a higher $k$ value (Figure \ref{fig:Linf_k_m-profile}). Changing either value has a relatively small affect on stock scale and relative stock status. Overall, the influence of male growth values is smaller than females. The model supported values of the variability at maximum age between 0.1 and 0.14 (Figure \ref{fig:CVold_f-profile-combo}). Larger values decreased overall popluation size a little, with more of an affect on the more recent biomass estimates, and had only small affect on relative stock status.


### Retrospective Analysis

A ten-year retrospective analysis was conducted by running the model and sequentially removing one year of data. Retrospective spawning output estimates were gnerally within the confidence intervals of the reference model (Figure \ref{fig:retro-ssb}), which also lead to consistent estimates of stock status among the retrospective scenarios, with no strong pattern (Figure \ref{fig:retro-depl}).

