# Management 

A salient aspect of the `r spp` stock assessment is how much the female portion of the population is affected by the fishery. Given any removal levels set will mostly influence spawning biomass directly, additional consideration about this asymmetry should be considered when setting catch levels.

## Harvest Projections and Decision Tables

A ten year projection of the reference model with removals in 2021 and 2022 equal to the recent average removals from 2017-2019 were run based on the category 2 time-varying buffer using $P^*$ = 0.45 for years 2023-2032 is provided in Table \ref{tab:project}.

The decision table (Table \ref{tab:dec-tab}) was constructed using natural mortality values (females and males assumed equivalent) to define the low and high states of nature. The likelihood profile of natural mortality was insufficent to capture undertainty in the base model. Natural mortality values for the staetes of nature were instead established by using the commonly applied lognormal treatment when estimating this parameter, with the mean (0.133, fixed in the base model) and standard deviation (0.438, a common default estimate of natural mortality uncertainty based on Hamel (2015)) used to find natural mortality values corresponding to the 12.5% and 87.5% quantiles (standard quantiles used in west coast decision tables). These values were 0.0804 and 0.22 for the low and high states of nature, respectively.

The catch rows in the table were based on two proposed catch streams:
  
  1. Removals based on P* = 0.45, sigma = 1 and time varying buffers specific to each state of nature 
  2. Removals based on P* = 0.40, sigma = 1 and time varying buffers from the base model

## Evaluation of Scientific Uncertainty

The estimated uncertainty in the base model around the `r endyr + 1` spawning output is $\sigma$ = `r round(model$Pstar_sigma,2)` and the uncertainty in the base model around the `r endyr + 1` OFL is $\sigma$ = `r round(model$OFL_sigma,2)`. The estimated model uncertainty was less than the category 2 groundfish data moderate assessment default value of  $\sigma$ = 1.0. 

## Future Research and Data Needs

`r Spp` is a relatively data-limited rockfish. More research and data collection would improve future assessments and address some sources of uncertainty. Below is a list of specific suggestions for future research:

1. More age and length data would continue to improve growth estimates, especially for females, and allow for the estimation of growth within the model. 
2. The maturity estimate used is old (30+ years ago) and was missing both the slope parameter or estimate of 95% maturity. An updated measure of functional maturity that gives a more complete consideration of the length or age-based maturity would be a major improvement. 
3. More work on dead discard estimates in recreational fisheries could benefit multiple rockfish species, especially smaller-sized species that are more prone to being thrown back and unidentified. 
4. The Hook and Line survey proved questionable for squarespot given their size. A survey for squarespot may be difficult to design given their small size and depths. Smaller hook size or other considerations will need to be evaluated in the event a survey for smaller rockfishes is desireable.
5. Hyperstability in length composition data (i.e., only catching the biggest individuals, thus unable to detect a decrease in relative stock size) should be explored via simulation testing in order to understand when catch and length models could suffer from the lack of contrast needed to detect stocks status.

