\clearpage

# Figures

<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "data_plot.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot')
```


<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "catch2 landings stacked.png"), 
caption = "Catches by fleet used in the base model",
label = 'catch')
```	
```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "catch2 landings stacked.png"), 
caption = "Catches by fleet used in the base model",
label = 'catch')
```	


<!-- ======================================================================================= -->
<!-- ****************   Recretaional and Commercial Length Samples    ********************** --> 
<!-- ======================================================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt1mkt0_page3.png"), 
caption = "Length composition data from recreational fleet",
label = 'rec-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_Comm_Rec.png"), 
caption = "Mean length for the recreational fleet with 95 percent confidence intervals",
label = 'rec-mean-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(comm_fig_loc, "squarespot_samples_ca_pacfin.png"), 
caption = "Sqaurespot rockfish commerical length sample frequencies by year",
label = 'squarespot_samples_ca_pacfin')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots/plots_2fleets", "comp_lendat_data_weighting_TA1.8_Commercial.png"), 
caption = "Mean length for the commercial fleet with 95 percent confidence intervals",
label = 'comm-mean-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt1mkt0_page3.png"), 
caption = "Bubble plot of length compositions for the commercial fleet with 95 percent confidence intervals",
label = 'bubble-comm-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_Comm_Rec.png"), 
caption = "Mean length for the commercial fleet with 95 percent confidence intervals",
label = 'rec-com-mean-len-data')
```

<!-- ====================================================================== -->
<!-- ************** NWFSC HKL Index & Length Sample  ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(survey_loc, "plots",  "Map_HL_Sites_lndscp.jpg"), 
caption = "NWFSC Hook and Line sampling sites where yellow sites indicate locations inside Cowcod Conservation Areas. Additionally, known substrate structure, depths, and areas under various management regulations are shown for the area south of Point Conception",
label = 'hkl-sites')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "hkl_cca_comparison.png"), 
caption = "NWFSC Hook and Line observations by year outside and inside the cowcod conservation area",
label = 'hkl-cca')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt2mkt0.png"), 
caption = "Length composition data from the NWFSC Hook and Line fleet",
label = 'hkl-len-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_HKL.png"), 
caption = "Mean length for NWFSC Hook and Line fleet with 95 percent confidence intervals",
label = 'mean-hkl-len-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index1_cpuedata_HKL.png"), 
caption = "Index of abundance for the NWFSC Hook and Line survey. Lines indicate 95 percent uncertainty interval around index values based on the model assumption of lognormal error. Thicker lines indicate input uncertainty before addition of estimated additional uncertainty parameter",
label = 'hkl-index')
```


<!-- ====================================================================== -->
<!-- ****************  NWFSC WCGBTS Length Samples   ********************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
#add_figure(
#filein = file.path(mod_loc, "plots", "comp_lendat_bubflt3mkt0.png"), 
#caption = "Length composition data from the NWFSC WCGBT survey",
#label = 'wcgbts-len-data')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_NWFSC_WCGBT.png"), 
#caption = "Mean length for NWFSC WCGBT survey with 95 percent confidence intervals",
#label = 'wcgbts-mean-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(survey_loc, "plots", "NWFSC WCGBTS_designed_based_index.png"), 
caption = "Design-based index of abundance for the NWFSC WCGBT survey",
label = 'wcgbts-dbindex')
```

<!-- ====================================================================== -->
<!-- *************************     Biology     **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "Length_Weight_All_w_Love_Ests.png"), 
caption = "Survey length-at-weight data with sex specific estimated fits and comparison to literature lengtha-at-weight values",
label = 'len-weight')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "doc_Data_Length_Age_by_Source.png"), 
caption = "Observed length-at-age by data source",
label = 'len-age-data')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "doc_Length_Age_by_Sex_RE.png"), 
caption = "Length-at-age estimated from the NWFSC WCGBT and Hook and Line survey data with sex specific estimated growth",
label = 'len-age')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio1_sizeatage.png"), 
caption = "Length at age in the beginning of the year in the ending year of the model",
label = 'len-age-ss')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio6_maturity.png"), 
caption = "Maturity as a function of  length",
label = 'maturity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio9_fecundity_len.png"), 
caption = "Fecundity as a function of length",
label = 'fecundity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "Mplots2021-03-26_09_05_49_Female.png"), 
caption = "Estimates of natural mortality for S. hopkinsi using longevity = 45 years and female VBGF parameters. Error bars are based on a lognormal distribution with SD = 0.2.",
label = 'M_female')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "Mdensityplots_FishLife_longevity.png"), 
caption = "Composite natural mortality distriubtion for S. hopkinsi using 4 longevity estimators each with a SD = 0.2 presuming a lognomral error distibution.",
label = 'M_composite_dists')
```

<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "sel01_multiple_fleets_length1.png"), 
caption = "Selectivity at length by fleet",
label = 'selex')
```
<!-- ================================================================= -->
<!-- ****************** Model Diagnostics **************************** --> 
<!-- ================================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "Jitter Results", "jitterplot.png"), 
caption = "Jitter runs for the squarespot reference model, with jitter run number on the x-axis and -log likelihood value on the y-axis. Blue dot are models that match the likelihood value of the reference model, while red dots deviate from the reference model. All red dots are above the blue dots, indicating no better fit to the reference model was found",
label = 'jitter_01')
```


<!-- ====================================================================== -->
<!-- ****************** Fit to the Length Data **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt1mkt0_page3.png"), 
caption = "Pearson residuals for combind recreational and commercial fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'rec-com-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_Comm_Rec.png"), 
caption = "Mean length for combined recreational and commercial lengths with 95 percent confidence intervals based on current samples sizes",
label = 'rec-com-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt2mkt0.png"), 
caption = "Pearson residuals for NWFSC Hook and Line fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'hkl-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_HKL.png"), 
caption = "Mean length for NWFSC Hook and Line lengths with 95 percent confidence intervals based on current samples sizes",
label = 'hkl-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__aggregated_across_time.png"), 
caption = "Aggregated length comps over all years",
label = 'agg-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_HKL.png"),
caption = "Fit to the NWFSC Hook and Line index of abundance",
label = 'hkl-index-fit')
```


<!-- ====================================================================== -->
<!-- ******************      Time Series       **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning output",
label = 'ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass",
label = 'tot-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts9_Relative_spawning_output_intervals.png"), 
caption = "Estimated time series of fraction of unfished spawning output",
label = 'depl')
```


<!-- ====================================================================== -->
<!-- *********************   Recruitment     ****************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
#add_figure(
#filein = file.path(mod_loc, "plots", "recdevs2_withbars.png"), 
#caption = "Estimated time series of recruitment deviations",
#label = 'rec-devs')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits')
```


<!-- ====================================================================== -->
<!-- ******************    Reference Points    **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the base case model. Values are based on the 2020
fishery selectivity and with steepness fixed at 0.72",
label = 'yield')
```



<!-- ====================================================================== -->
<!-- ******************       Sensitivity     ***************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_data, "Sensi_logREplot_SB_Dep_F_MSY.png"),
caption = "Log relative change (log((Model_sensi-Model_ref)/Model_ref)) in data treatment for 5 derived quantities. Colored boxes indicate 95 percent confidence interval of the reference model",
label = 'sensi-data-RE')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_data, "compare2_spawnbio_uncertainty.png"),
caption = "Spawning biomass time series by data treatment compared to the reference model.",
label = 'sensi-data-ssb')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_data, "compare4_Bratio_uncertainty.png"),
caption = "Relative spawning biomass time series by data treatment compared to the reference model.",
label = 'sensi-data-depl')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_modspecs, "Sensi_logREplot_SB_Dep_F_MSY.png"),
caption = "Log relative change (log((Model_sensi-Model_ref)/Model_ref)) in data treatment for 5 derived quantities. Colored boxes indicate 95 percent confidence interval of the reference model",
label = 'sensi-modspec-RE')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_modspecs, "compare2_spawnbio_uncertainty.png"),
caption = "Spawning biomass time series by data treatment compared to the reference model.",
label = 'sensi-modspec-ssb')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_modspecs, "compare4_Bratio_uncertainty.png"),
caption = "Relative spawning biomass time series by data treatment compared to the reference model.",
label = 'sensi-modspec-depl')
```

<!-- ============================================================================== -->
<!-- ******************      Likelihood Profiles      ***************************** --> 
<!-- ============================================================================== -->

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_SR_LN(R0)"),  "piner_panel_SR_LN(R0).png"), 
#caption = "Change in the negative log-likelihood across a range of log(R0) values",
#label = 'r0-profile')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare1_spawnbio.png"), 
#caption = "Change in the estimate of spawning output across a range of log(R0) values",
#label = 'r0-ssb')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare3_Bratio.png"), 
#caption = "Change in the estimate of fraction unfished across a range of log(R0) values",
#label = 'r0-depl')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_SR_BH_steep"),  "piner_panel_SR_BH_steep.png"), 
#caption = "Change in the negative log-likelihood across a range of steepness values",
#label = 'h-profile')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare1_spawnbio.png"), 
#caption = "Change in the estimate of spawning output across a range of steepness values",
#label = 'h-ssb')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare3_Bratio.png"), 
#caption = "Change in the estimate of fraction unfished across a range of steepness values",
#label = 'h-depl')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_NatM_p_1_Fem_GP_1"),  "piner_panel_NatM_p_1_Fem_GP_1.png"), 
#caption = "Change in the negative log-likelihood across a range of female natural mortality values",
#label = 'm-profile')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
#caption = "Change in the estimate of spawning output across a range of female natural mortality values",
#label = 'm-ssb')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare3_Bratio.png"), 
#caption = "Change in the estimate of fraction unfished across a range of female natural values",
#label = 'm-depl')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_L_at_Amax_Fem_GP_1"),  "piner_panel_L_at_Amax_Fem_GP_1.png"), 
#caption = "Change in the negative log-likelihood across a range of female maximum length values",
#label = 'linf-profile')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_L_at_Amax_Fem_GP_1"),  "L_at_Amax_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
#caption = "Change in the estimate of spawning output across a range of female maximum length values",
#label = 'linf-ssb')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_L_at_Amax_Fem_GP_1"),  "L_at_Amax_Fem_GP_1_trajectories_compare3_Bratio.png"), 
#caption = "Change in the estimate of fraction unfished across a range of female maximum length values",
#label = 'linf-depl')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_VonBert_K_Fem_GP_1"),  "piner_panel_VonBert_K_Fem_GP_1.png"), 
#caption = "Change in the negative log-likelihood across a range of female k values",
#label = 'k-profile')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_VonBert_K_Fem_GP_1"),  "VonBert_K_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
#caption = "Change in the estimate of spawning output across a range of female k values",
#label = 'k-ssb')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_profile_VonBert_K_Fem_GP_1"),  "VonBert_K_Fem_GP_1_trajectories_compare3_Bratio.png"), 
#caption = "Change in the estimate of fraction unfished across a range of female k values",
#label = 'k-depl')
```

<!-- ====================================================================== -->
<!-- ******************     Retrospectives    ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_retro"),  "compare2_spawnbio_uncertainty.png"), 
#caption = "Change in the estimate of spawning output when the most recent 5 years of data area removed sequentially",
#label = 'retro-ssb')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(paste0(mod_loc, "_retro"),  "compare4_Bratio_uncertainty.png"),
#caption = "Change in the estimate of fraction unfished when the most recent 5 years of data area removed sequentially",
#label = 'retro-depl')
```

\newpage